### ISSUE TITLE
Introduction texts

### ISSUE THREAD

**Issue by az-ihsan** [az-ihsan/MDMC-NEP-top-level-ontology#12]
It would be great if someone can first write the introduction texts for the front page of repository as of now it looks like empty. 
Or else,  we can put in our meeting agendan to generate some README.md

**Comment by az-ihsan** [comment]
for example [here](https://github.com/az-ihsan/dislocation-ontology/blob/master/README.md)

**Comment by rossellaaversa** [comment]
I can do it

**Comment by az-ihsan** [comment]
This is closed by the addition of README.md file in the repository [here](https://github.com/az-ihsan/MDMC-NEP-top-level-ontology/blob/master/README.md)
