### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by rossellaaversa** [az-ihsan/MDMC-NEP-top-level-ontology#13]
Dataset (from glossary): collection of scientifically related Research Data which can be Raw Data , Analysed Data, or other Datasets, each described by their related Metadata. The components of a Dataset remain individually identifiable within the Dataset.

**Comment by rossellaaversa** [comment]
According to the glossary, @mpanighel says that dataset is a container, a collection, of whatever data: raw data, analysed data, an other dataset... AND metadata.
It is an entity generated by the action of composing together data and metadata.
The definition of the entity must allow for RECURSIVE action: dataset 3 can be generated composing together dataset 1 and dataset 2

**Comment by rossellaaversa** [comment]
Better: 
any element of the dataset, and dataset itself, is described by metadata. 
According to the definition, dataset is described by metadata. But also the components of a dataset (e.g. raw data or analysed data) remain individually identifiable, which means they are described by metadata. 
So a good workaround is to define: 
dataset = a collection of data (e.g. raw data and/or analysed data)
dataset has metadata
raw data has metadata
analysed data has metadata

**Comment by rossellaaversa** [comment]
@EOsmenaj  suggested that Dataset can be "Collection" as in prov. 
If we say that dataset is a subclass of collection, the recursivity can be managed using "had member": collection is an entity which can "hadMember" of the entity.
@az-ihsan please check this

**Comment by az-ihsan** [comment]
I took a look again into #5, in particular in [here](https://github.com/az-ihsan/MDMC-NEP-top-level-ontology/issues/5#issuecomment-1025632076) and changed a couple class restrictions.

**Comment by az-ihsan** [comment]
On 01.02.2022 will have the agenda on discussing the PR #16 (Dataset, PublicationData, ResearchData, etc)

**Comment by az-ihsan** [comment]
as #16, we close the issue.
