### ISSUE TITLE
[Term Discussion] Publication Data

### ISSUE THREAD

**Issue by az-ihsan** [az-ihsan/MDMC-NEP-top-level-ontology#5]
According to the definition of Publication Data 
> **Publication Data** is a **Research Data** intended to appear in a scientific publication.

It is true that Publication data is a subclass of Research Data. 

But, the comment of Publication data is part of Research Data and Analysed Data is somewhat confusing because if suppose Publication Data is a subclass of Analyzed data then it inherently also a research data. 

I would suggest that there is a connection between Publication Data and Dataset (disjoint union of Analysed Data, Metadata, and Raw Data) connection would be:
`PublicationData hasDataset Dataset`

**Comment by rossellaaversa** [comment]
Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data. 
Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".

**Comment by az-ihsan** [comment]
We agree that `PublicationData hasDataset Dataset`

**Comment by az-ihsan** [comment]
comment: There is something missing regarding the activity generate the Publication Data from Dataset.

**Comment by az-ihsan** [comment]
Dataset is disjunction class of Research Data + Metadata

**Comment by rossellaaversa** [comment]
Publication data = a Dataset associated to a Paper
we must know the provenance: 
Dataset = some Data + Metadata
Data wasGenerated by User using analysis/instrument/...

**Comment by rossellaaversa** [comment]
if we want to add another Agent that puslishes the PublicationData, that's ok

**Comment by az-ihsan** [comment]
> Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data.
> Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
> Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".

According to the discussion on 25.01.2022
```
ResearchData: prov:Entity
    hasMetadata some Metadata
    prov:wasAttributedTo some ResearchUser
AnalysedData: ResearchData
    prov:wasGeneratedBy some DataAnalysis
RawData: ResearchData
    prov:wasGeneratedBy some Measurement
PublicationData: prov:Entity
    isStoredBy some DataRepository
    prov:wasAttributedTo some ResearchUser
    prov:wasDerivedFrom some Dataset
Dataset: prov:Collection
    prov:hadMember some AnalysedData, RawData
    hasMetadata some Metadata
    prov:hadMember some Dataset
    isStoredBy some DataCollaborationPlatform
Metadata: prov:Entity
    isStoredBy some MetadataRepository
    prov:wasAttributedTo ResearchUser
```

**Comment by rossellaaversa** [comment]
> > Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data.
> > Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
> > Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".
> 
> According to the discussion on 25.01.2022
> 
> ```
> ResearchData: prov:Entity
>     hasMetadata some Metadata
>     prov:wasAttributedTo some ResearchUser
> AnalysedData: ResearchData
>     prov:wasGeneratedBy some DataAnalysis
> RawData: ResearchData
>     prov:wasGeneratedBy some Measurement
> PublicationData: prov:Entity
>     isStoredBy some DataRepository
>     prov:wasAttributedTo some ResearchUser
>     prov:wasDerivedFrom some Dataset
> Dataset: prov:Collection
>     prov:hadMember some AnalysedData, RawData
>     hasMetadata some Metadata
>     prov:hadMember some Dataset
>     isStoredBy some DataCollaborationPlatform
> Metadata: prov:Entity
>     isStoredBy some MetadataRepository
>     prov:wasAttributedTo ResearchUser
> ```

I agree. As a small remark, I would add that Dataset isStoredBy some DataCollaborationPlatform but also by some DataRepository

**Comment by mpanighel** [comment]
> > Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data.
> > Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
> > Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".
> 
> According to the discussion on 25.01.2022
> 
> ```
> ResearchData: prov:Entity
>     hasMetadata some Metadata
>     prov:wasAttributedTo some ResearchUser
> AnalysedData: ResearchData
>     prov:wasGeneratedBy some DataAnalysis
> RawData: ResearchData
>     prov:wasGeneratedBy some Measurement
> PublicationData: prov:Entity
>     isStoredBy some DataRepository
>     prov:wasAttributedTo some ResearchUser
>     prov:wasDerivedFrom some Dataset
> Dataset: prov:Collection
>     prov:hadMember some AnalysedData, RawData
>     hasMetadata some Metadata
>     prov:hadMember some Dataset
>     isStoredBy some DataCollaborationPlatform
> Metadata: prov:Entity
>     isStoredBy some MetadataRepository
>     prov:wasAttributedTo ResearchUser
> ```

Sounds good. Maybe an alternative could also be consider `PublicationData` a subclass of `Dataset`?

**Comment by az-ihsan** [comment]
> 

Sure, i will add it into the newest iteration.

**Comment by az-ihsan** [comment]
> > > Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data.
> > > Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
> > > Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".
> > 
> > 
> > According to the discussion on 25.01.2022
> > ```
> > ResearchData: prov:Entity
> >     hasMetadata some Metadata
> >     prov:wasAttributedTo some ResearchUser
> > AnalysedData: ResearchData
> >     prov:wasGeneratedBy some DataAnalysis
> > RawData: ResearchData
> >     prov:wasGeneratedBy some Measurement
> > PublicationData: prov:Entity
> >     isStoredBy some DataRepository
> >     prov:wasAttributedTo some ResearchUser
> >     prov:wasDerivedFrom some Dataset
> > Dataset: prov:Collection
> >     prov:hadMember some AnalysedData, RawData
> >     hasMetadata some Metadata
> >     prov:hadMember some Dataset
> >     isStoredBy some DataCollaborationPlatform
> > Metadata: prov:Entity
> >     isStoredBy some MetadataRepository
> >     prov:wasAttributedTo ResearchUser
> > ```
> 
> Sounds good. Maybe an alternative could also be consider `PublicationData` a subclass of `Dataset`?

I think based on our discussion back then, we rather put the `PublicationData` prov:wasDerivedFrom `Dataset` rather than subclass of `Dataset` because to get a `PublicationData` there is a curation process from `Dataset` which we model in prov as *was derived from*.

**Comment by az-ihsan** [comment]
> > Research Data is data in a research context. Raw Data and Analysed Data are subclasses of Research Data.
> > Dataset is Research Data + Metadata. For example Raw Dataset = Raw Data + Metadata, Analysed Dataset = Analysed Data + Metadata
> > Publication Data is a subclass on Research Data by definition (as it is all or a part of Raw/Analysed data), but I agree that in practice you don't publish data without metadata, so Publication Data could be related directly to Dataset. In real case, Publication Data will be on a persistent Data Repository as standalone, so I agree in connecting it with "hasDataset".
> 
> According to the discussion on 25.01.2022
> 
> ```
> ResearchData: prov:Entity
>     hasMetadata some Metadata
>     prov:wasAttributedTo some ResearchUser
> AnalysedData: ResearchData
>     prov:wasGeneratedBy some DataAnalysis
> RawData: ResearchData
>     prov:wasGeneratedBy some Measurement
> PublicationData: prov:Entity
>     isStoredBy some DataRepository
>     prov:wasAttributedTo some ResearchUser
>     prov:wasDerivedFrom some Dataset
> Dataset: prov:Collection
>     prov:hadMember some AnalysedData, RawData
>     hasMetadata some Metadata
>     prov:hadMember some Dataset
>     isStoredBy some DataCollaborationPlatform
> Metadata: prov:Entity
>     isStoredBy some MetadataRepository
>     prov:wasAttributedTo ResearchUser
> ```

I think the question to you @mpanighel and @rossellaaversa whether all of the classes i defined above should have the attribution to `ResearchUser`?

**Comment by rossellaaversa** [comment]
I agree with the wasAttributedTo `ResearchUser` for all the classes. 
I assume that `AnalysedData` or `RawData` don't have `ResearchUser` because they are subclassed of `ResearchData`. 
Is is possible to have multiple or different `ResearchUser`? E.g., `RawData` wasAttributedTo user1 and `AnalysedData` wasAttributedTo user2?

Still missing that `Dataset` isStoredBy some `DataCollaborationPlatform` but also by some `DataRepository`

**Comment by az-ihsan** [comment]
> I agree with the wasAttributedTo `ResearchUser` for all the classes. I assume that `AnalysedData` or `RawData` don't have `ResearchUser` because they are subclassed of `ResearchData`. Is is possible to have multiple or different `ResearchUser`? E.g., `RawData` wasAttributedTo user1 and `AnalysedData` wasAttributedTo user2?
Yes this would be fine since they are a subclass of `ResearchData`
> 
> Still missing that `Dataset` isStoredBy some `DataCollaborationPlatform` but also by some `DataRepository`
Sure i will add it now, sorry i missed it.

**Comment by az-ihsan** [comment]
```
ResearchData: prov:Entity
    hasMetadata some Metadata
    prov:wasAttributedTo some ResearchUser
AnalysedData: ResearchData
    prov:wasGeneratedBy some DataAnalysis
RawData: ResearchData
    prov:wasGeneratedBy some Measurement
PublicationData: prov:Entity
    isStoredBy some DataRepository
    prov:wasAttributedTo some ResearchUser
    prov:wasDerivedFrom some Dataset
Dataset: prov:Collection
    prov:hadMember some AnalysedData, RawData
    hasMetadata some Metadata
    prov:wasAttributedTo some ResearchUser
    prov:hadMember some Dataset
    isStoredBy some DataCollaborationPlatform
    isStoredBy some DataRepository
Metadata: prov:Entity
    isStoredBy some MetadataRepository
    prov:wasAttributedTo ResearchUser
```

**Comment by mpanighel** [comment]
> ```
> ResearchData: prov:Entity
>     hasMetadata some Metadata
>     prov:wasAttributedTo some ResearchUser
> AnalysedData: ResearchData
>     prov:wasGeneratedBy some DataAnalysis
> RawData: ResearchData
>     prov:wasGeneratedBy some Measurement
> PublicationData: prov:Entity
>     isStoredBy some DataRepository
>     prov:wasAttributedTo some ResearchUser
>     prov:wasDerivedFrom some Dataset
> Dataset: prov:Collection
>     prov:hadMember some AnalysedData, RawData
>     hasMetadata some Metadata
>     prov:wasAttributedTo some ResearchUser
>     prov:hadMember some Dataset
>     isStoredBy some DataCollaborationPlatform
>     isStoredBy some DataRepository
> Metadata: prov:Entity
>     isStoredBy some MetadataRepository
>     prov:wasAttributedTo ResearchUser
> ```
> 
> If everyone is good with this, i will merge the PR #16

Thanks, ok also for me!

**Comment by az-ihsan** [comment]
Thanks for your feedback, ill merge it now

**Comment by az-ihsan** [comment]
as #16, we close the issue.

**Comment by rossellaaversa** [comment]
Dataset is the "selection" of raw/analysed data (according to scientific problem)
We publish Dataset
Publication Data: Dataset needed to validate the results presented in a Scientific Publication or appearing in it. It may include Raw Data, Analysed Data and all the relevant Metadata on Measurement and Data Analysis to validate them.
