### ISSUE TITLE
[Term Discussion] Sample Componenet Synthesis

### ISSUE THREAD

**Issue by az-ihsan** [az-ihsan/MDMC-NEP-top-level-ontology#6]
Is Sample Component Synthesis also a subclass of Experiment? like the one of Sample Preparation.

**Comment by rossellaaversa** [comment]
The definition of Experiment is an activity to investigate or **produce** Sample, So I would say yes, at least in general (there are cases in which the sample is synthesised by a manufacturer, but this is a special case).
